# -*- coding: utf-8 -*-
"""Google Play Store EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1garXWKF004Lu3vOqIhbfhYZVSfCm2nMS

# **Project Name**   - Google Play Store EDA

##### **Project Type**    - EDA
##### **Contribution**    - Individual

##**Introduction**

The Google Play Store hosts millions of mobile applications across various categories, serving billions of users worldwide. Understanding application characteristics such as ratings, installs, pricing, app size, and monetization strategies can provide valuable insights into factors influencing app success.

This exploratory data analysis (EDA) aims to uncover patterns in the Google Play Store dataset through statistical summaries and visualizations. The analysis focuses on understanding user preferences, category performance, pricing strategies, and relationships between key application attributes.

##**Business Objective**

The primary objectives of this analysis are to:

- Identify categories with the highest user adoption and engagement.
Compare the performance of free and paid applications.
- Analyze how ratings, reviews, installs, pricing, and app size influence app popularity.
- Examine different monetization strategies, including ad-supported and paid applications.
- Generate actionable business insights that can assist developers in making data-driven decisions regarding app development and marketing.

##**Dataset Cleaning & Understanding**
"""

# Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset
from google.colab import drive
drive.mount('/content/drive')
playstore=pd.read_csv('/content/drive/MyDrive/Dataset/Google-Playstore.csv')

# Print First 5 Rows of Dataset
playstore.head()

# Print Last 5 Rows of Dataset
playstore.tail()

# Dataset Rows & Columns count of Dataset
playstore.shape

# Dataset Columns of Dataset
playstore.columns

# Dataset Info
playstore.info()

# Statistical summary of dataset
playstore.describe()

"""## **Descriptive Statistics**

The summary statistics provide an overview of the numerical features in the dataset. App ratings range from 0 to 5, while install counts and rating counts vary widely across applications. This indicates that some apps are significantly more popular than others, which will be explored further using visualizations.

## **Dataset Variable Description**

| Variable | Data Type | Description |
|----------|-----------|-------------|
| **App Name** | Object | Name of the application available on the Google Play Store. |
| **App Id** | Object | Unique identifier assigned to each application. |
| **Category** | Object | Category under which the application is listed. |
| **Rating** | Float | Average user rating (0–5). |
| **Rating Count** | Float | Total number of user ratings received. |
| **Installs** | Object | Install range displayed on the Play Store. |
| **Minimum Installs** | Float | Minimum estimated installs. |
| **Maximum Installs** | Integer | Maximum estimated installs. |
| **Free** | Boolean | Indicates whether the application is free or paid. |
| **Price** | Float | Price of the application. |
| **Currency** | Object | Currency used for the app price. |
| **Size** | Object | Size of the application. |
| **Minimum Android** | Object | Minimum Android version required. |
| **Developer Id** | Object | Unique identifier of the developer. |
| **Developer Website** | Object | Official website of the developer. |
| **Developer Email** | Object | Developer contact email. |
| **Released** | Object | Application release date. |
| **Last Updated** | Object | Most recent update date. |
| **Content Rating** | Object | Recommended age group for the application. |
| **Privacy Policy** | Object | Link to the privacy policy. |
| **Ad Supported** | Boolean | Indicates whether the app contains advertisements. |
| **In App Purchases** | Boolean | Indicates whether in-app purchases are available. |
| **Editors Choice** | Boolean | Indicates whether the app received Google's Editor's Choice badge. |
| **Scraped Time** | Object | Timestamp when the dataset was collected. |
"""

# Missing Values/Null Values Count of Dataset
playstore.isnull().sum()

"""## **Missing Value Analysis**

Missing values are primarily concentrated in developer-related information, such as developer website, developer email, and privacy policy, along with a small number of missing application metadata fields. Since these variables are not central to the objectives of this analysis, they will not significantly impact the exploratory analysis.

##**Data Wrangling**
"""

# Dataset Duplicate Value Count
playstore.duplicated().sum()

"""## **Duplicate Analysis**

The dataset contains **0 duplicate rows**, so no duplicate records needed to be removed.
"""

#Calculating the mean percentage of missing values
playstore.isnull().mean()*100

# Drop columns as they are not useful for further analysis
playstore.dropna(
    subset=['App Name','Rating','Rating Count','Minimum Installs','Currency','Size', 'Minimum Android','Developer Id','Developer Email',],
    inplace=True
)

# impute Developer Website column with 'Unknown'
playstore['Developer Website'] = playstore['Developer Website'].fillna('Unknown')

# Dropped identifier/contact columns as they do not contribute to business analysis.
playstore.drop(
    columns=[
        'App Id',
        'Developer Website',
        'Developer Email',
        'Privacy Policy','Installs'
    ],
    inplace=True
)

# Converting Released datatype column to datetime datatype
playstore['Released']=pd.to_datetime(playstore['Released'],errors='coerce')

# Converting 'Last Updated' datatype column to datetime datatype
playstore['Last Updated']=pd.to_datetime(playstore['Last Updated'])

# Converting 'Scrapped Time' datatype column to datetime datatype
playstore['Scraped Time']=pd.to_datetime(playstore['Scraped Time'])

# Custom function to convert size column to numeric column
def convert_size(size):
    if size == 'Varies with device':
        return np.nan
    size = size.replace(',', '')

    if 'M' in size:
        return float(size.replace('M',''))

    if 'G' in size:
        return float(size.replace('G','')) * 1024

playstore['Size_MB'] = playstore['Size'].apply(convert_size)

# Create a 2 × 3 grid of subplots to visualize the distribution and identify potential outliers in numerical features.
fig, axes = plt.subplots(2, 3, figsize=(12,10))

# Boxplot showing the distribution of app ratings.
sns.boxplot(ax=axes[0,0], data=playstore, x='Rating', color='skyblue')
axes[0,0].set_title("Distribution of Rating")

# Boxplot showing the distribution of rating counts.
sns.boxplot(ax=axes[0,1], data=playstore, x='Rating Count', color='skyblue')
axes[0,1].set_title("Distribution of Rating Count")

# Boxplot showing the distribution of minimum installs.
sns.boxplot(ax=axes[0,2], data=playstore, x='Minimum Installs', color='red')
axes[0,2].set_title("Distribution of Minimum Installs")

# Boxplot showing the distribution of maximum installs.
sns.boxplot(ax=axes[1,0], data=playstore, x='Maximum Installs', color='green')
axes[1,0].set_title("Distribution of Maximum Installs")

# Boxplot showing the distribution of app prices.
sns.boxplot(ax=axes[1,1], data=playstore, x='Price', color='green')
axes[1,1].set_title("Distribution of Price")

# Boxplot showing the distribution of application size.
sns.boxplot(ax=axes[1,2], data=playstore, x='Size_MB', color='green')
axes[1,2].set_title("Distribution of App Size")

# Adjust subplot spacing for a cleaner layout.
plt.tight_layout()

# Display all boxplots.
plt.show()

"""## **Outlier Analysis**

* The boxplots reveal that Rating Count, Minimum Installs, and Maximum Installs contain a large number of extreme outliers, indicating that only a small number of applications receive exceptionally high user engagement while the majority attract relatively fewer users.

* Price also contains several outliers, as a limited number of premium applications are priced significantly higher than the majority of paid apps, which are concentrated at lower price points.

* App Size (MB) exhibits moderate variability with a few large applications acting as outliers, although most applications remain within a relatively compact size range.

* In contrast, Ratings show comparatively fewer extreme values since application ratings are naturally bounded between 0 and 5, resulting in a more stable distribution.

* Overall, the distributions of installs, reviews, and pricing are highly right-skewed, suggesting that median and percentile-based statistics are more appropriate than mean values when analyzing these variables.

##**Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables**
"""

# Distribution of Rating
# Creating a figure with width 12 and height 6 inches
plt.figure(figsize=(12,6))
# Filtering rows where ratings are greater than 0
rating_data=playstore[playstore['Rating']>0]
# Create a histogram to show the Distribution of ratings
sns.histplot(data=rating_data,x='Rating',kde=True,bins=20)
# Add a title to the chart
plt.title('Distribution of Rating')
# Set the label for the x-axis
plt.xlabel('Rating',fontsize=12)
# Automatically adjust spacing to prevent overlap
plt.tight_layout()
# Display the chart
plt.show()

"""**Insight(s) found from the chart**

* Most applications have ratings between 4.0 and 4.8, indicating that highly rated apps dominate the Play Store.
* Very few applications have ratings below 3.5, suggesting either poor-quality apps are removed or users tend to rate satisfactory apps more often.
* The distribution is negatively skewed towards higher ratings, showing an overall positive user perception.
* Since ratings are concentrated within a narrow range, ratings alone may not be sufficient to differentiate successful applications.
"""

# Create a figure with width 12 and height 6 inches
plt.figure(figsize=(12,6))

# Filtering rows where ratings are greater than 0
rating_data = playstore[playstore['Rating'] > 0]

# Create a scatter plot to show rating vs rating count
sns.scatterplot(
    data=rating_data,
    x='Rating',
    y='Rating Count',
    hue='Rating'
)

# Format Rating Count into K, M, and B
from matplotlib.ticker import FuncFormatter

def human_format(y, pos):
    if y >= 1_000_000_000:
        return f'{y/1_000_000_000:.1f}B'
    elif y >= 1_000_000:
        return f'{y/1_000_000:.1f}M'
    elif y >= 1_000:
        return f'{y/1_000:.0f}K'
    else:
        return str(int(y))

plt.gca().yaxis.set_major_formatter(FuncFormatter(human_format))

# Add a title to the chart
plt.title('Rating vs Rating Count', fontsize=16)

# Set the label for the x-axis
plt.xlabel('Rating', fontsize=12)

# Set the label for the y-axis
plt.ylabel('Rating Count', fontsize=12)

# Automatically adjust spacing to prevent overlap
plt.tight_layout()

# Display the chart
plt.show()

playstore[['Rating','Rating Count']].corr()

"""**Insight(s) found from the chart**

* The scatter plot indicates a very weak positive relationship between app ratings and the number of user reviews, suggesting that highly rated apps do not always attract a large volume of feedback.

* Several apps with excellent ratings have relatively few reviews, while some apps with average ratings accumulate a significant number of reviews, indicating that ratings alone are not a reliable indicator of popularity.
"""

# Create a figure with width 12 and height 6 inches
plt.figure(figsize=(12,6))
# Create a count plot to show the category distribution
sns.countplot(data=playstore,x='Category',hue='Category')
# Add a title to the chart
plt.title('Distribution of category',fontsize=16)
# Set the label for the x-axis
plt.xlabel('Category',fontsize=12)
# Rotate x-axis labels by 90 degree for better visibility
plt.xticks(rotation=90)
# Set the label for the y-axis
plt.ylabel('Count',fontsize=12)
# Automatically adjust spacing to prevent overlap
plt.tight_layout()
# Display the chart
plt.show()

"""**Insight(s) found from the chart**

* Categories such as Education, Business, and Lifestyle contain the largest number of applications.
* A higher number of apps indicates greater competition within these categories.
* Developers entering highly populated categories need stronger differentiation and better marketing strategies to stand out.
* Less crowded categories may provide opportunities for niche applications with lower competitive pressure.
"""

category_rating=playstore.groupby('Category')['Rating'].mean().reset_index().sort_values(by='Rating',ascending=False).head(25)

# Create a figure with width 12 and height 6 inches
plt.figure(figsize=(12,6))
# Create a bar plot to show average rating across categories
sns.barplot(data=category_rating,x='Category',y='Rating',hue='Category')
# Add a title to the chart
plt.title('Distribution of category',fontsize=16)
# Set the label for the x-axis
plt.xlabel('Category',fontsize=12)
# Rotate x-axis labels by 90 degree
plt.xticks(rotation=90)
# Set the label for the y-axis
plt.ylabel('Count',fontsize=12)
# Automatically adjust spacing to prevent overlap
plt.tight_layout()
# Display the chart
plt.show()

"""**Insight(s) found from the chart**

Although Role Playing has relatively fewer apps, it has the highest average rating (3.4). In contrast, the Education category contains the largest number of apps but has a lower average rating (2.5), suggesting that a larger number of apps does not necessarily translate into better user satisfaction.
"""

# Set the figure size for better readability.
plt.figure(figsize=(12,6))

# Create a count plot comparing the number of free and paid applications.
ax = sns.countplot(data=playstore,x='Free',hue='Free',legend=False)

# Add the exact count value on top of each bar.
for container in ax.containers:
    ax.bar_label(container, fmt='%d', fontsize=11)

# Add a descriptive title to the chart.
plt.title('Free vs Paid Apps', fontsize=16)

# Label the x-axis.
plt.xlabel('Free', fontsize=12)

# Keep category labels horizontal for better readability.
plt.xticks(rotation=0)

# Label the y-axis.
plt.ylabel('Number of Apps', fontsize=12)

# Adjust layout to prevent clipping.
plt.tight_layout()

# Display the visualization.
plt.show()

"""**Insight(s) found from the chart**

* Free applications significantly outnumber paid applications on the Play Store.
This reflects the dominance of the freemium business model, where developers attract users through free downloads and monetize using advertisements or in-app purchases.
* The relatively small proportion of paid apps suggests that users are generally reluctant to pay upfront for mobile applications.
* Developers targeting large audiences often prefer free distribution to maximize user acquisition.
"""

# Create a figure with width 12 and height 6 inches
plt.figure(figsize=(8,6))
# Create a boxplot to compare the maximum installs of free and paid apps.
sns.boxplot(
    data=playstore,
    x='Free',
    y='Maximum Installs'
)
# Use a log scale to better visualize large variations in install counts.
plt.yscale('log')
# Add a title to the chart
plt.title("Maximum Installs: Free vs Paid Apps")
# Set the label for the x-axis
plt.xlabel("Free App")
# Set the label for the y-axis
plt.ylabel("Maximum Installs (Log Scale)")
# Display the chart
plt.show()

"""**Insight(s) found from the chart**

* Free applications receive substantially higher installs compared to paid applications.
* The absence of an upfront purchase requirement lowers the entry barrier, encouraging more downloads.
* Paid applications typically target niche users who prioritize premium features over mass adoption.
* This result highlights the importance of pricing strategy in influencing application reach.
"""

# Create a figure with width 12 and height 6 inches
plt.figure(figsize=(8,6))
# Create a boxplot to compare the maximum installs of ad-free and ad-supported apps.
sns.boxplot(data=playstore,x='Ad Supported',y='Maximum Installs')
# Use a log scale to better visualize large variations in install counts.
plt.yscale('log')
# Add a title to the chart
plt.title("Maximum Installs: Ad Supported Apps")
# Set the label for the x-axis
plt.xlabel("Free App")
# Set the label for the y-axis
plt.ylabel("Maximum Installs (Log Scale)")
# Display the chart
plt.show()

"""**Insight(s) found from the chart**

* Advertisement-supported applications generally achieve higher installs than non-ad-supported apps.
* This indicates that developers often monetize popular free applications through advertising revenue.
* Users appear more willing to tolerate advertisements than to pay upfront for applications.
* Ad-supported monetization remains one of the most widely adopted business models in the mobile application ecosystem.
"""

# Create a cross-tabulation showing the percentage distribution of ad-supported apps within free and paid application categories.
cross = pd.crosstab(playstore['Free'], playstore['Ad Supported'], normalize='index') * 100
# Plot the percentage distribution as a stacked bar chart.
cross.plot(kind='bar', stacked=True, figsize=(12,6))
# Add a title to the chart
plt.title("Percentage of Ad-Supported Apps by Pricing Model")
# Set the label for the x-axis
plt.xlabel("Free App")
# Set the label for the y-axis
plt.ylabel("Percentage")
# Add a legend to distinguish ad-supported and non-ad-supported apps.
plt.legend(title="Ad Supported")
# Display the chart
plt.show()

"""**Insight(s) found from the chart**

* The majority of free applications are advertisement-supported, reinforcing the popularity of the freemium model.
* Paid applications show much lower dependency on advertisements because revenue is generated directly through purchases.
* The relationship between pricing strategy and monetization strategy becomes evident through this comparison.
* Developers typically choose monetization models based on their target audience and business objectives
"""

avg_installs = playstore.groupby("Category")["Maximum Installs"].mean().reset_index().sort_values(by='Maximum Installs',ascending=False).head(10)
avg_installs.columns = ["Category", "Average Installs"]
avg_installs

# Calculate the average maximum installs for each category
# and select the top 10 categories with the highest average installs.
avg_installs = playstore.groupby("Category")["Maximum Installs"] \
    .mean() \
    .reset_index() \
    .sort_values(by='Maximum Installs', ascending=False) \
    .head(10)

# Rename columns for better readability.
avg_installs.columns = ["Category", "Average Installs"]

# Import required libraries for formatting axis labels and visualization.
from matplotlib.ticker import FuncFormatter
import matplotlib.pyplot as plt
import seaborn as sns

# Format large numbers into human-readable form
# (e.g., 1.5B, 500M, 200K).
def human_format(y, pos):
    if y >= 1_000_000_000:
        return f'{y/1_000_000_000:.1f}B'
    elif y >= 1_000_000:
        return f'{y/1_000_000:.0f}M'
    elif y >= 1_000:
        return f'{y/1_000:.0f}K'
    else:
        return str(int(y))

# Set the figure size for better readability.
plt.figure(figsize=(12,7))

# Create a bar chart showing the top 10 categories
# by average installs per application.
ax = sns.barplot(
    data=avg_installs,
    x="Category",
    y="Average Installs",
    hue="Category",
    legend=False
)

# Format the y-axis labels into K, M, and B notation.
ax.yaxis.set_major_formatter(FuncFormatter(human_format))

# Rotate x-axis labels to avoid overlapping.
plt.xticks(rotation=45, ha='right')

# Add chart title.
plt.title("Top 10 Categories by Average Installs per App", fontsize=16)

# Label the x-axis.
plt.xlabel("Category", fontsize=12)

# Label the y-axis.
plt.ylabel("Average Installs", fontsize=12)

# Adjust layout to prevent clipping of labels.
plt.tight_layout()

# Display the visualization.
plt.show()

"""**Insight(s) found from the chart**

* Certain categories achieve substantially higher average installs despite containing fewer applications.
* This suggests that user demand varies considerably across categories and is not solely determined by the number of available apps.
* Categories with high average installs represent markets with greater consumer engagement and larger audiences.
"""

# Filter only paid applications (Price > 0).
paid_apps = playstore[playstore["Price"] > 0]

# Calculate the median price for each category and select the top 15 categories with the highest median app price.
category_analysis = (paid_apps.groupby('Category')['Price'].median().reset_index().sort_values(by='Price', ascending=False).head(15))

# Display the resulting category-wise median price analysis.
category_analysis

# Create a figure with width 12 and height 8 inches
plt.figure(figsize=(12,8))
# Create a bar plot to show top 15 highly paid categories
sns.barplot(data=category_analysis,x='Price',y='Category',hue='Category')
# Add a title to the chart
plt.title("TOP 15 Paid Apps Category")
# Display the chart
plt.show()

"""**Insight(s) found from the chart**

* Average pricing differs considerably across categories, indicating distinct pricing strategies.
* Professional or specialized categories often command higher prices because users perceive greater value.
* Entertainment-focused categories generally adopt lower pricing to encourage purchases from a broader audience.
* Pricing should align with user expectations and the perceived usefulness of the application.
"""

# Set the figure size for better visualization.
plt.figure(figsize=(10,6))

# Create a scatter plot to examine the relationship
# between app size and maximum installs.
sns.scatterplot(
    data=playstore,
    x="Size_MB",
    y="Maximum Installs",
    alpha=0.4,      # Reduce point opacity to minimize overlap.
    s=30            # Set marker size for better readability.
)

# Apply a logarithmic scale to the y-axis to better visualize the highly skewed install counts.
plt.yscale("log")

# Add a descriptive title to the chart.
plt.title("App Size vs Maximum Installs")

# Label the x-axis.
plt.xlabel("App Size (MB)")

# Label the y-axis.
plt.ylabel("Maximum Installs (Log Scale)")

# Adjust layout to prevent clipping of labels.
plt.tight_layout()

# Display the scatter plot.
plt.show()

playstore[["Size_MB", "Maximum Installs"]].corr()

"""**Insight(s) found from the chart**

* The relationship between application size and installs appears weak, suggesting that file size alone does not strongly influence download decisions.
* Both small and large applications are capable of achieving high install counts.
* Other factors such as functionality, usability, ratings, and marketing likely play a much larger role in determining popularity.
* Optimizing application size is beneficial for user experience but should not be considered the primary driver of installs.
"""

# Select numerical columns for correlation analysis.
numeric_cols = ["Rating","Rating Count","Price","Maximum Installs","Size"]
# Compute the correlation matrix
corr = playstore[numeric_cols].corr(numeric_only=True)

# Set the figure size for better readability.
plt.figure(figsize=(12,6))

# Create a heatmap to visualize the correlation
# between numerical features in the dataset.
sns.heatmap(
    corr,
    annot=True,          # Display correlation values inside each cell.
    cmap="coolwarm",     # Use a diverging color palette to distinguish positive and negative correlations.
    fmt=".2f",           # Display correlation values up to two decimal places.
    linewidths=0.5       # Add grid lines between cells for better clarity.
)

# Add a descriptive title to the heatmap.
plt.title("Correlation Matrix of Numerical Features")

# Display the visualization.
plt.show()

"""* Most numerical variables exhibit weak to moderate correlations, indicating that no single metric fully explains application success.
* Rating Count and Installs demonstrate a positive relationship because popular applications naturally accumulate more user feedback.
* Ratings themselves show relatively weak correlation with installs, suggesting that highly rated apps are not necessarily the most downloaded.
* Application success depends on multiple interacting factors rather than any single variable.
"""

# Randomly sample 10,000 records to improve plotting performance while preserving the overall data distribution.
sample = playstore.sample(10000, random_state=42)

# Create a pairplot to explore pairwise relationships and distributions among selected numerical features.
sns.pairplot(sample[["Rating","Price","Size","Maximum Installs"]])

"""* Pairwise relationships confirm the patterns observed in individual analyses.
* Rating Count and Installs display a noticeable positive association, while Ratings remain relatively independent.
* The presence of strong outliers is visible across several numerical variables, emphasizing the highly skewed nature of Play Store data.

##**Business Recommendations**

###**Improve app discoverability and user engagement**

  Although most applications have ratings above 4.0, many apps have very few or no reviews. This indicates that a large number of potentially good apps struggle with visibility rather than quality. Developers should invest in App Store Optimization (ASO), targeted marketing, and in-app review prompts to increase exposure and user feedback.

###**Prioritize high-demand categories**

  The Video Players & Editors category records the highest average installs per app, demonstrating exceptionally strong user demand. Developers seeking maximum reach should consider categories with proven adoption potential while still evaluating competitive intensity.

###**Explore underserved categories**

  Categories such as Comics, Music, and Parenting contain relatively few applications, suggesting lower competition. High-quality, differentiated apps in these categories may achieve faster visibility and user adoption.

###**Compete on quality in saturated markets**

  The Education category has the largest number of apps, yet it does not appear among the top categories by average installs per app. This suggests that simply entering a large category is not enough; developers must differentiate through superior content quality, user experience, and feature innovation.

###**Adopt an appropriate monetization strategy**

  Free apps dominate both app count and install volume, indicating that users strongly prefer applications without an upfront cost. For mass-market products, a freemium model (free download with ads or in-app purchases) is likely the most effective strategy. Paid apps appear to perform better in value-driven categories such as Health & Fitness and Lifestyle, where users are more willing to pay for ongoing utility.

###**Focus on multiple drivers of app success**

  The analysis shows a very weak relationship between Rating and Rating Count, and app size exhibits little influence on install volume. Therefore, app popularity is driven by a combination of factors—including category demand, visibility, marketing effectiveness, user engagement, and product quality—rather than any single metric.

## **Conclusion**

* This exploratory data analysis provided valuable insights into the characteristics and performance of applications available on the Google Play Store. The analysis revealed that the platform is dominated by free applications, which consistently achieve significantly higher install counts than paid apps, highlighting the effectiveness of the freemium business model.

* Application success was found to depend on multiple factors rather than a single metric. While most apps maintain ratings above 4.0, the relationship between ratings and user engagement remains weak, indicating that visibility, category demand, marketing efforts, and user experience play a much greater role in driving app popularity. Similarly, app size showed little influence on install counts, suggesting that users prioritize application value over file size.

* Category-level analysis identified both highly competitive and underserved markets. Although the Education category contains the largest number of applications, it does not rank among the highest categories in terms of average installs per app, indicating intense competition. In contrast, categories such as Video Players & Editors demonstrate exceptional user demand, while Comics, Music, and Parenting offer opportunities for developers due to lower competition.

* Overall, the findings emphasize that successful mobile applications require a balanced combination of high-quality products, effective monetization strategies, strong discoverability, and continuous user engagement. These insights can assist developers, businesses, and stakeholders in making informed decisions regarding app development, pricing, marketing, and market positioning within the highly competitive Google Play Store ecosystem.
"""